
# app service archetype
hub_internet_ingress:
  agw: false
  firewall_ingress: false
  frontdoor: false
hub_internet_egress:
  firewall_egress: false
hub_intranet_ingress:
  agw: false
  firewall_ingress: false
hub_intranet_egress:
  firewall_egress: false
management:
  bastion_host: false
  vm: false
devops:
  containter_instance: true
project:
  acr: false
  ai_foundry_enterprise: false
  aks_avm_ptn: false
  apim: true
  app_service: true
  app_service_intranet: false
  app_service_windows: false
  azure_open_ai: false
  container_instance: true
  cosmos_db_mongo: false
  cosmos_db_sql: false
  data_explorer: true
  event_hubs: true
  iot_hub: true
  keyvault: true
  linux_function_app: true
  logic_app: false
  mssql: true
  redis_cache: false
  search_service: false
  service_bus: false
  storage_account: true
  stream_analytics: true
  vm: false