
# app service archetype
hub_internet_ingress:
  agw: false
  firewall_ingress: false
  frontdoor: false
hub_internet_egress:
  firewall_egress: false
hub_intranet_ingress:
  agw: false
  firewall_ingress: false
hub_intranet_egress:
  firewall_egress: false
management:
  bastion_host: false
  vm: false
devops:
  container_instance: true
project:
  acr: false
  ai_foundry_enterprise: false
  ai_search_service: false
  aks_avm_ptn: false
  apim: false
  app_service: true
  container_instance: false
  cosmos_db_mongo: false
  cosmos_db_sql: false
  data_explorer: false
  event_hubs: false
  iot_hub: false
  keyvault: true
  linux_function_app: false
  logic_app: false
  mssql: true
  redis_cache: false
  search_service: false
  ai_search_service: false
  service_bus: false
  storage_account: true
  stream_analytics: false
  vm: false