  resource_group_name: "gcci-platform" # DO NOT CHANGE
  log_analytics_workspace_resource_group_name: "gcci-agency-law"  # DO NOT CHANGE
  log_analytics_workspace_name: "gcci-agency-workspace"  # DO NOT CHANGE
  # virtual network - leave empty if there is no such virtual network  
  vnets:
    hub_ingress_internet: 
      name: "gcci-vnet-ingress-internet"     
      cidr: "100.127.0.0/24" 
    hub_egress_internet:  
      name: "gcci-vnet-egress-internet"     
      cidr: "100.127.1.0/24" 
    hub_ingress_intranet:  
      name: "gcci-vnet-ingress-intranet"    
      cidr: "10.20.0.0/25"
    hub_egress_intranet:  
      name: "gcci-vnet-egress-intranet"     
      cidr: "10.20.1.0/25" 
    management:  
      name: "gcci-vnet-management"     
      cidr: "100.127.3.0/24" 
    project:  
      name:    
      cidr: 
    devops:  
      name: 
      cidr: 
