  resource_group_name: "gcci-platform" # DO NOT CHANGE
  log_analytics_workspace_resource_group_name: "gcci-agency-law"  # DO NOT CHANGE
  log_analytics_workspace_name: "gcci-agency-workspace"  # DO NOT CHANGE
  # virtual network - leave empty if there is no such virtual network  
  vnets:
    hub_ingress_internet: 
      name:     
      cidr: 
    hub_egress_internet:  
      name:     
      cidr:
    hub_ingress_intranet:  
      name: 
      cidr: 
    hub_egress_intranet:  
      name: 
      cidr: 
    management:  
      name: 
      cidr: 
    project:  
      name: "gcci-vnet-project"     
      cidr: "100.64.0.0/23" 
    devops:  
      name: "gcci-vnet-devops"   
      cidr: "100.127.4.0/24"  
