apiVersion: v1
kind: Service
metadata:
  name: internal-internet-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "UserNodePoolSubnet"
spec:
  type: LoadBalancer
  ports:
  - port: 8082
  selector:
    app: internal-internet-app
