apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  # nodeSelector:
  #  "agentnodepool": poolappsintranet  
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: hashicorp/http-echo:0.2.3  # acr image: e.g. aoaiuatacrran33n.azurecr.io/http-echo:0.2.3
        args:
        - "-text=Hello World i am intranet"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  # This ensures the service is internal
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "UserNodePoolIntranetSubnet" # "WebIntranetSubnet" # this ensure front end ip is in a particular subnet. Default is SystemNodePoolSubnet    
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5678
  selector:
    app: hello-world
